services:
  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"  # Change host port to 3001 to avoid conflicts

  test:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - app
    command: npm run test