version: '3.8'

services:
  # Nuxt 應用服務與測試服務合併在同一容器中
  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm run dev & npm run test"  # 啟動 Nuxt 開發服務器並執行測試
    ports:
      - "3000:3000"  # 開放端口 3000